# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
do_sth <- function(some_vector) {
    .Call(`_RcppCopyExample_do_sth`, some_vector)
}

#' @export
do_sth_more <- function(some_list) {
    .Call(`_RcppCopyExample_do_sth_more`, some_list)
}

#' @export
create_vector_list_with_one_modification <- function(v) {
    .Call(`_RcppCopyExample_create_vector_list_with_one_modification`, v)
}

#' @export
create_vector_list_with_two_modifications <- function(v) {
    .Call(`_RcppCopyExample_create_vector_list_with_two_modifications`, v)
}

